version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/tests"               # 👈 path to requirements.txt
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    ignore:
      - dependency-name: "robocop_rules_setup.txt"
    groups:
      robotframework-libraries:
        patterns:
          - "robotframework*"
      python-general:
        patterns:
          - "*"