name: Build Robot Framework Docker Image For integration-tests repo

on:
  push:
    branches:
      - 'main'

jobs:
  build-docker-image:
    runs-on: ubuntu-20.04
    
    env:
      DOCKER_IMAGE_VERSION: 1.0.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install Robot Framework
        run: |
          python -m pip install --upgrade pip
          pip install robotframework

      - name: Install Robot Framework Libraries
        run: |
          python -m pip install -r requirements.txt
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build And Push Docker Image
        run: |
          docker build -t integration-tests/robot-docker-image:${{ env.DOCKER_IMAGE_VERSION }} .
          docker push integration-tests/robot-docker-image:${{ env.DOCKER_IMAGE_VERSION }}
          #docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
